### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davebonds** [agentevolution/wp-listings#1]
- [x] Single listing template conditional output
- [x] Single listing template tabs section
- [x] Decide on default fields
- [x] Genesis conditional - move loop to function
- [x] Beef up widget output
- [x] Default CSS (http://kyleschaeffer.com/development/simple-jquery-tabs-template/)
- [x] Archive CSS
- [x] Widget CSS
- [x] Gallery metabox??? - http://www.billerickson.net/wordpress-add-custom-fields-media-gallery/ http://codex.wordpress.org/Function_Reference/wp_editor
- [x] add code from single post template, ap taxonomy reorder
- [x] Stop template_include from overriding parent theme template with single_template
- [x] GAP integration on single listing template
- [x] Add conditional for GAP integration on non-Genesis themes-
- [x] echo map field (embed or shortcode)
- [x] Form submission function (no need for form plugin)
- [x] Deregister widget css option?
- [x] test listing widget on our themes

== 1.1 ==
- Map?? (http://www.9bitstudios.com/2013/09/create-a-google-maps-shortcode-in-wordpress/). Needs geocoding - http://martyspellerberg.com/address-geocode-wordpress-plugin/

== Other Notes ==
- New theme can have it's own custom template.
